version: '2.2'
services:
  kafka:
    env_file:
      - .env

  workers:
    image: workers
    container_name: workers
    build: 
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        exposed_http_port: 3000
        exposed_grpc_port: 2999
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - apps
      - db
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["workers"]

  users:
    image: users
    container_name: users
    build: 
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        exposed_http_port: $AUTH_PORT
        exposed_grpc_port: 2999
    env_file:
      - .env
    ports:
      - $AUTH_PORT:$AUTH_PORT
    volumes:
      - ./logs:/app/logs
    networks:
      - apps
      - db
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: ["users"]

  currencies:
    image: currencies
    container_name: currencies
    build: 
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        exposed_http_port: $CURRENCIES_PORT
        exposed_grpc_port: $CURRENCIES_GRPC_PORT
    env_file:
      - .env
    ports:
      - $CURRENCIES_PORT:$CURRENCIES_PORT
      - $CURRENCIES_GRPC_PORT:$CURRENCIES_GRPC_PORT
    volumes:
      - ./logs:/app/logs
    networks:
      - apps
      - db
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -sSk https://127.0.0.1:$CURRENCIES_PORT || exit 1
      interval: 30s
      timeout: 30s
      retries: 6
    command: ["currencies"]

  transaction_categories:
    image: transaction_categories
    container_name: transaction_categories
    build: 
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        exposed_http_port: $CATEGORIES_PORT
        exposed_grpc_port: $CATEGORIES_GRPC_PORT
    env_file:
      - .env
    ports:
      - $CATEGORIES_PORT:$CATEGORIES_PORT
      - $CATEGORIES_GRPC_PORT:$CATEGORIES_GRPC_PORT
    volumes:
      - ./logs:/app/logs
    networks:
      - apps
      - db
      - elastic
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      es01:
        condition: service_started
    healthcheck:
      test: curl -sSk https://127.0.0.1:$CATEGORIES_PORT || exit 1
      interval: 30s
      timeout: 30s
      retries: 6
    command: ["transaction-categories"]

  transactions:
    image: transactions
    container_name: transactions
    build: 
      dockerfile: ./docker/Dockerfile
      context: .
      args:
        exposed_http_port: $TRANSACTIONS_PORT
        exposed_grpc_port: 2999
    env_file:
      - .env
    ports:
      - $TRANSACTIONS_PORT:$TRANSACTIONS_PORT
    volumes:
      - ./logs:/app/logs
    networks:
      - apps
      - db
      - kafka
      - elastic
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      es01:
        condition: service_started
      currencies:
        condition: service_healthy
      transaction_categories:
        condition: service_healthy
    command: ["transactions"]

networks:
  apps:
    driver: bridge
  elastic:
    driver: bridge
  db:
    driver: bridge
  kafka:
    driver: bridge
